# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'properties_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PropertiesWindow(object):
    def setupUi(self, PropertiesWindow):
        PropertiesWindow.setObjectName("PropertiesWindow")
        PropertiesWindow.resize(401, 301)
        self.centralwidget = QtWidgets.QWidget(PropertiesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(180, 20, 181, 221))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 179, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        PropertiesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PropertiesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 21))
        self.menubar.setObjectName("menubar")
        PropertiesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PropertiesWindow)
        self.statusbar.setObjectName("statusbar")
        PropertiesWindow.setStatusBar(self.statusbar)


        top_widget = QtWidgets.QWidget()
        top_layout = QtWidgets.QVBoxLayout()

        for i in range(10):
            group_box = QtWidgets.QWidget()
            layout = QtWidgets.QHBoxLayout(group_box)
            box = QtWidgets.QCheckBox(group_box)
            layout.addWidget(box)
            top_layout.addWidget(group_box)

        top_widget.setLayout(top_layout)
        self.scrollArea.setWidget(top_widget)

        self.retranslateUi(PropertiesWindow)
        QtCore.QMetaObject.connectSlotsByName(PropertiesWindow)

    def retranslateUi(self, PropertiesWindow):
        _translate = QtCore.QCoreApplication.translate
        PropertiesWindow.setWindowTitle(_translate("PropertiesWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PropertiesWindow = QtWidgets.QMainWindow()
    ui = Ui_PropertiesWindow()
    ui.setupUi(PropertiesWindow)
    PropertiesWindow.show()
    sys.exit(app.exec_())
